### ISSUE TITLE
pregunta 1

### ISSUE THREAD

**Issue by billygl** [cafuentes1/lolocar-test#1]
Necesitamos un servicio web REST en ExpressJS que permita obtener la siguiente respuesta:
{
	"message": "Hola, Lolocar"
}
En caso la petición incluya un nombre, por ejemplo, 
un nombre igual a candidatio
 éste debe mostrar:
{
	"message": "Hola, Candidatio"
}
Como es urgente, esperamos que sea resuelto en el menor tiempo posible pero con la mayor calidad posible.

**Comment by cafuentes1** [comment]
Ok, calculo tomará unos 15 min

**Comment by cafuentes1** [comment]
Solución en: https://github.com/cafuentes1/lolocar-test/tree/fix/issue-1
